# ============================================================
# Vaulten — ProGuard / R8 rules
# ============================================================

# Keep line numbers in stack traces (useful for crash reports)
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Keep all annotations (required by Retrofit, Room, serialization, etc.)
-keepattributes *Annotation*,Signature,Exceptions,InnerClasses,EnclosingMethod

# ============================================================
# Autofill Service — MUST keep class name (referenced in AndroidManifest)
# ============================================================
-keep class * extends android.service.autofill.AutofillService { *; }

# ============================================================
# Retrofit
# ============================================================
-dontwarn retrofit2.**
-keep class retrofit2.** { *; }
-keep interface retrofit2.** { *; }
# Keep Retrofit API interfaces and their method signatures
-keep interface com.wilove.vaulten.data.remote.** { *; }

# ============================================================
# OkHttp
# ============================================================
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }
-dontwarn org.conscrypt.**
-dontwarn org.bouncycastle.**
-dontwarn org.openjsse.**

# ============================================================
# kotlinx.serialization
# ============================================================
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt

# Keep serializer companions generated by the plugin
-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# Keep all @Serializable data classes used with Retrofit / export-import
-keep,includedescriptorclasses class com.wilove.vaulten.data.remote.model.** { *; }
-keep,includedescriptorclasses class com.wilove.vaulten.data.export.** { *; }

-keepclassmembers @kotlinx.serialization.Serializable class ** {
    *** Companion;
    *** INSTANCE;
    kotlinx.serialization.KSerializer serializer(...);
}

# ============================================================
# Room
# ============================================================
-keep class * extends androidx.room.RoomDatabase { *; }
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao interface * { *; }
-keep class com.wilove.vaulten.data.local.** { *; }
-dontwarn androidx.room.**

# ============================================================
# ViewModel (keep constructors so ViewModelProvider.Factory works)
# ============================================================
-keepclassmembers class * extends androidx.lifecycle.ViewModel {
    <init>(...);
}

# ============================================================
# Jetpack Security Crypto (EncryptedSharedPreferences)
# ============================================================
-keep class androidx.security.crypto.** { *; }
-dontwarn androidx.security.crypto.**

# ============================================================
# Biometric
# ============================================================
-keep class androidx.biometric.** { *; }
-dontwarn androidx.biometric.**

# ============================================================
# Jetpack Credentials
# ============================================================
-keep class androidx.credentials.** { *; }
-dontwarn androidx.credentials.**
-dontwarn com.google.android.libraries.identity.**

# ============================================================
# Timber
# ============================================================
-dontwarn org.slf4j.**

# ============================================================
# Kotlin coroutines
# ============================================================
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
-dontwarn kotlinx.coroutines.**
